/** All navigable routes in the app with Vietnamese labels */
export const APP_ROUTES: { value: string; label: string }[] = [
  { value: '/', label: '/ (Tổng quan)' },
  { value: '/import/new', label: '/import/new (Nhập hàng mới)' },
  { value: '/import/history', label: '/import/history (Lịch sử nhập hàng)' },
  { value: '/export/new', label: '/export/new (Bán hàng mới)' },
  { value: '/export/history', label: '/export/history (Lịch sử bán hàng)' },
  { value: '/products', label: '/products (Sản phẩm)' },
  { value: '/inventory', label: '/inventory (Tồn kho)' },
  { value: '/categories', label: '/categories (Danh mục)' },
  { value: '/suppliers', label: '/suppliers (Nhà cung cấp)' },
  { value: '/customers', label: '/customers (Khách hàng)' },
  { value: '/debt', label: '/debt (Công nợ)' },
  { value: '/cash-book', label: '/cash-book (Sổ quỹ)' },
  { value: '/reports', label: '/reports (Báo cáo)' },
  { value: '/returns', label: '/returns (Trả hàng)' },
  { value: '/stock-transfer', label: '/stock-transfer (Chuyển kho)' },
  { value: '/invoice-template', label: '/invoice-template (Mẫu hóa đơn)' },
  { value: '/e-invoice', label: '/e-invoice (Hóa đơn điện tử)' },
  { value: '/branches', label: '/branches (Chi nhánh)' },
  { value: '/users', label: '/users (Nhân viên)' },
  { value: '/audit-logs', label: '/audit-logs (Nhật ký)' },
  { value: '/advertisements', label: '/advertisements (Quảng cáo)' },
  { value: '/landing-admin', label: '/landing-admin (Landing page)' },
  { value: '/subscription', label: '/subscription (Gói dịch vụ)' },
  { value: '/install-app', label: '/install-app (Cài đặt ứng dụng)' },
  { value: '/affiliate', label: '/affiliate (Affiliate)' },
  { value: '/tax-policy', label: '/tax-policy (Chính sách thuế)' },
];
