// Sample products for each website template preview
export interface SampleProduct {
  name: string;
  price: string;
  image: string; // emoji placeholder
  tag?: string;
}

export const TEMPLATE_SAMPLE_PRODUCTS: Record<string, SampleProduct[]> = {
  phone_store: [
    { name: 'iPhone 16 Pro Max 256GB', price: '34.990.000₫', image: '📱', tag: 'Hot' },
    { name: 'Samsung Galaxy S25 Ultra', price: '31.990.000₫', image: '📱' },
    { name: 'iPhone 15 128GB', price: '19.990.000₫', image: '📱', tag: 'Giảm giá' },
    { name: 'Ốp lưng MagSafe', price: '490.000₫', image: '🛡️' },
    { name: 'Sạc nhanh 20W Apple', price: '490.000₫', image: '🔌' },
  ],
  laptop_store: [
    { name: 'MacBook Pro M4 14 inch', price: '42.990.000₫', image: '💻', tag: 'Mới' },
    { name: 'Dell XPS 15', price: '35.990.000₫', image: '💻' },
    { name: 'Lenovo ThinkPad X1 Carbon', price: '32.990.000₫', image: '💻' },
    { name: 'Chuột Logitech MX Master 3S', price: '2.290.000₫', image: '🖱️' },
    { name: 'Bàn phím cơ Keychron K2', price: '1.990.000₫', image: '⌨️' },
  ],
  accessories_store: [
    { name: 'AirPods Pro 2', price: '5.990.000₫', image: '🎧', tag: 'Bán chạy' },
    { name: 'Sạc dự phòng Anker 20.000mAh', price: '790.000₫', image: '🔋' },
    { name: 'Cáp Type-C 2m Baseus', price: '190.000₫', image: '🔌' },
    { name: 'Ốp lưng iPhone 16', price: '290.000₫', image: '🛡️' },
    { name: 'Kính cường lực 9H', price: '150.000₫', image: '📋' },
  ],
  electronics_store: [
    { name: 'Tivi Samsung 55" QLED', price: '15.990.000₫', image: '📺', tag: 'Hot' },
    { name: 'Máy giặt LG Inverter 9kg', price: '8.990.000₫', image: '🫧' },
    { name: 'Tủ lạnh Panasonic 322L', price: '10.990.000₫', image: '❄️' },
    { name: 'Điều hòa Daikin 1.5HP', price: '12.990.000₫', image: '🌬️' },
    { name: 'Máy hút bụi Dyson V12', price: '14.990.000₫', image: '🧹' },
  ],
  fashion_store: [
    { name: 'Áo blazer nữ cao cấp', price: '1.290.000₫', image: '🧥', tag: 'New' },
    { name: 'Quần jean slim fit', price: '690.000₫', image: '👖' },
    { name: 'Đầm dạ hội sang trọng', price: '2.490.000₫', image: '👗' },
    { name: 'Áo sơ mi nam Oxford', price: '590.000₫', image: '👔' },
    { name: 'Túi xách da thời trang', price: '1.890.000₫', image: '👜' },
  ],
  shoes_store: [
    { name: 'Nike Air Max 90', price: '3.290.000₫', image: '👟', tag: 'Bán chạy' },
    { name: 'Adidas Ultraboost 23', price: '4.190.000₫', image: '👟' },
    { name: 'Giày cao gót nữ 7cm', price: '890.000₫', image: '👠' },
    { name: 'Dép quai ngang Birkenstock', price: '2.490.000₫', image: '🩴' },
    { name: 'Giày da công sở nam', price: '1.590.000₫', image: '👞' },
  ],
  cosmetics_store: [
    { name: 'Son MAC Matte Lipstick', price: '590.000₫', image: '💄', tag: 'Hot' },
    { name: 'Kem chống nắng Anessa SPF50+', price: '490.000₫', image: '🧴' },
    { name: 'Serum Vitamin C 20%', price: '790.000₫', image: '💧' },
    { name: 'Phấn nền Estée Lauder', price: '1.290.000₫', image: '✨' },
    { name: 'Nước tẩy trang Bioderma', price: '350.000₫', image: '🫧' },
  ],
  spa_store: [
    { name: 'Gói massage body 90 phút', price: '590.000₫', image: '💆', tag: 'Phổ biến' },
    { name: 'Chăm sóc da mặt cao cấp', price: '890.000₫', image: '🧖' },
    { name: 'Tắm trắng collagen', price: '1.290.000₫', image: '✨' },
    { name: 'Triệt lông laser', price: '1.990.000₫', image: '💫' },
    { name: 'Gội đầu dưỡng sinh', price: '290.000₫', image: '🧴' },
  ],
  salon_store: [
    { name: 'Cắt tóc nam tạo kiểu', price: '150.000₫', image: '💇', tag: 'Phổ biến' },
    { name: 'Nhuộm tóc cao cấp', price: '590.000₫', image: '🎨' },
    { name: 'Uốn tóc Hàn Quốc', price: '790.000₫', image: '💇‍♀️' },
    { name: 'Phục hồi tóc Keratin', price: '890.000₫', image: '✨' },
    { name: 'Gội massage đầu', price: '100.000₫', image: '🧴' },
  ],
  watch_store: [
    { name: 'Rolex Submariner', price: '250.000.000₫', image: '⌚', tag: 'Luxury' },
    { name: 'Omega Seamaster', price: '120.000.000₫', image: '⌚' },
    { name: 'Casio G-Shock GA-2100', price: '2.990.000₫', image: '⌚' },
    { name: 'Apple Watch Ultra 2', price: '21.990.000₫', image: '⌚' },
    { name: 'Đồng hồ Daniel Wellington', price: '3.490.000₫', image: '⌚' },
  ],
  jewelry_store: [
    { name: 'Nhẫn kim cương 1 carat', price: '89.000.000₫', image: '💍', tag: 'Luxury' },
    { name: 'Dây chuyền vàng 18K', price: '15.990.000₫', image: '📿' },
    { name: 'Bông tai ngọc trai', price: '4.990.000₫', image: '✨' },
    { name: 'Vòng tay bạc S925', price: '890.000₫', image: '💎' },
    { name: 'Nhẫn cưới đôi vàng trắng', price: '12.990.000₫', image: '💍' },
  ],
  restaurant_store: [
    { name: 'Bò Wagyu nướng A5', price: '890.000₫', image: '🥩', tag: 'Đặc biệt' },
    { name: 'Set sashimi tổng hợp', price: '590.000₫', image: '🍣' },
    { name: 'Phở bò tái chín đặc biệt', price: '89.000₫', image: '🍜' },
    { name: 'Cơm gà Hải Nam', price: '79.000₫', image: '🍗' },
    { name: 'Kem Tiramisu homemade', price: '69.000₫', image: '🍰' },
  ],
  cafe_store: [
    { name: 'Cà phê sữa đá', price: '39.000₫', image: '☕', tag: 'Best Seller' },
    { name: 'Latte art đặc biệt', price: '55.000₫', image: '☕' },
    { name: 'Matcha latte', price: '49.000₫', image: '🍵' },
    { name: 'Bánh croissant bơ Pháp', price: '45.000₫', image: '🥐' },
    { name: 'Smoothie trái cây tươi', price: '59.000₫', image: '🍹' },
  ],
  boba_store: [
    { name: 'Trà sữa trân châu đường đen', price: '45.000₫', image: '🧋', tag: 'Hot' },
    { name: 'Trà đào cam sả', price: '39.000₫', image: '🍑' },
    { name: 'Matcha đá xay', price: '49.000₫', image: '🍵' },
    { name: 'Sữa tươi trân châu', price: '35.000₫', image: '🥛' },
    { name: 'Trà vải oolong', price: '42.000₫', image: '🫖' },
  ],
  realestate_store: [
    { name: 'Căn hộ Vinhomes 2PN', price: '3.500.000.000₫', image: '🏠', tag: 'Nổi bật' },
    { name: 'Nhà phố liền kề 5x20m', price: '8.900.000.000₫', image: '🏘️' },
    { name: 'Đất nền khu đô thị mới', price: '2.100.000.000₫', image: '📐' },
    { name: 'Biệt thự ven sông', price: '15.000.000.000₫', image: '🏡' },
    { name: 'Officetel cho thuê 35m²', price: '8.000.000₫/tháng', image: '🏢' },
  ],
  car_showroom: [
    { name: 'Mercedes C300 AMG 2025', price: '1.929.000.000₫', image: '🚗', tag: 'Mới' },
    { name: 'Toyota Camry 2.5Q', price: '1.310.000.000₫', image: '🚗' },
    { name: 'VinFast VF8 Plus', price: '1.259.000.000₫', image: '🚗' },
    { name: 'Hyundai Tucson 2.0 AT', price: '899.000.000₫', image: '🚙' },
    { name: 'Honda CR-V L 1.5 Turbo', price: '1.099.000.000₫', image: '🚙' },
  ],
  motorbike_showroom: [
    { name: 'Honda SH 150i ABS', price: '105.990.000₫', image: '🏍️', tag: 'Bán chạy' },
    { name: 'Yamaha NVX 155 VVA', price: '52.990.000₫', image: '🏍️' },
    { name: 'Honda Vision 2025', price: '31.990.000₫', image: '🛵' },
    { name: 'Vespa Sprint 150 S', price: '89.900.000₫', image: '🛵' },
    { name: 'Honda Winner X ABS', price: '49.990.000₫', image: '🏍️' },
  ],
  furniture_store: [
    { name: 'Sofa góc da Ý cao cấp', price: '25.990.000₫', image: '🛋️', tag: 'Hot' },
    { name: 'Bàn ăn gỗ óc chó 6 ghế', price: '18.990.000₫', image: '🪑' },
    { name: 'Giường ngủ bọc nệm King', price: '12.990.000₫', image: '🛏️' },
    { name: 'Tủ quần áo 3 cánh', price: '8.990.000₫', image: '🚪' },
    { name: 'Kệ tivi phòng khách', price: '5.990.000₫', image: '📺' },
  ],
  construction_store: [
    { name: 'Xi măng Hà Tiên PCB40', price: '95.000₫/bao', image: '🧱', tag: 'Phổ biến' },
    { name: 'Thép Pomina D10', price: '15.500₫/kg', image: '🔩' },
    { name: 'Gạch ốp 60x60 cao cấp', price: '189.000₫/m²', image: '🏗️' },
    { name: 'Sơn Dulux nội thất 5L', price: '590.000₫', image: '🎨' },
    { name: 'Ống nước PPR D25', price: '35.000₫/m', image: '🔧' },
  ],
  hotel_store: [
    { name: 'Phòng Deluxe Sea View', price: '1.500.000₫/đêm', image: '🏨', tag: 'Phổ biến' },
    { name: 'Suite Honeymoon', price: '3.500.000₫/đêm', image: '🏨' },
    { name: 'Phòng Standard Twin', price: '800.000₫/đêm', image: '🛏️' },
    { name: 'Villa Private Pool', price: '5.990.000₫/đêm', image: '🏡' },
    { name: 'Gói nghỉ dưỡng 3N2Đ', price: '4.990.000₫', image: '🌴' },
  ],
  minimart_store: [
    { name: 'Nước suối Aquafina 500ml', price: '6.000₫', image: '💧' },
    { name: 'Mì gói Hảo Hảo thùng 30', price: '99.000₫', image: '🍜', tag: 'Giá sỉ' },
    { name: 'Sữa Vinamilk 1L', price: '32.000₫', image: '🥛' },
    { name: 'Bánh Oreo hộp 133g', price: '25.000₫', image: '🍪' },
    { name: 'Nước giặt Omo 3.7kg', price: '159.000₫', image: '🧴' },
  ],
  grocery_store: [
    { name: 'Gạo ST25 túi 5kg', price: '129.000₫', image: '🍚', tag: 'Bán chạy' },
    { name: 'Dầu ăn Neptune 2L', price: '79.000₫', image: '🫗' },
    { name: 'Nước mắm Phú Quốc 500ml', price: '45.000₫', image: '🧉' },
    { name: 'Trứng gà ta hộp 10', price: '35.000₫', image: '🥚' },
    { name: 'Đường Biên Hòa 1kg', price: '22.000₫', image: '🧂' },
  ],
  wholesale_store: [
    { name: 'Thùng nước ngọt Coca 24 lon', price: '195.000₫', image: '🥤', tag: 'Giá sỉ' },
    { name: 'Bột giặt OMO 6kg (x5)', price: '750.000₫', image: '📦' },
    { name: 'Mì tôm Hảo Hảo (x10 thùng)', price: '890.000₫', image: '🍜' },
    { name: 'Sữa tươi TH True Milk (x48)', price: '580.000₫', image: '🥛' },
    { name: 'Giấy vệ sinh Pulppy 12 cuộn', price: '89.000₫', image: '🧻' },
  ],
  general_store: [
    { name: 'Áo thun unisex basic', price: '199.000₫', image: '👕', tag: 'Mới' },
    { name: 'Balo laptop chống nước', price: '390.000₫', image: '🎒' },
    { name: 'Đèn LED để bàn', price: '250.000₫', image: '💡' },
    { name: 'Bình giữ nhiệt 500ml', price: '290.000₫', image: '🫙' },
    { name: 'Ốp lưng điện thoại', price: '99.000₫', image: '📱' },
  ],
  repair_service: [
    { name: 'Thay màn hình iPhone 15', price: '2.990.000₫', image: '🔧', tag: 'Phổ biến' },
    { name: 'Thay pin iPhone chính hãng', price: '890.000₫', image: '🔋' },
    { name: 'Sửa bo mạch laptop', price: '1.500.000₫', image: '🔩' },
    { name: 'Vệ sinh laptop toàn bộ', price: '250.000₫', image: '🧹' },
    { name: 'Cài đặt phần mềm', price: '150.000₫', image: '💿' },
  ],
  training_center: [
    { name: 'Khóa IELTS 6.5 - 3 tháng', price: '8.500.000₫', image: '🎓', tag: 'Phổ biến' },
    { name: 'Lớp tiếng Hàn sơ cấp', price: '3.990.000₫', image: '📚' },
    { name: 'Khóa Marketing Online', price: '2.990.000₫', image: '💻' },
    { name: 'Lớp vẽ cho thiếu nhi', price: '1.500.000₫', image: '🎨' },
    { name: 'Khóa lập trình Python', price: '5.990.000₫', image: '🐍' },
  ],
  clinic_store: [
    { name: 'Khám tổng quát cơ bản', price: '500.000₫', image: '🏥', tag: 'Phổ biến' },
    { name: 'Xét nghiệm máu 12 chỉ số', price: '350.000₫', image: '🩸' },
    { name: 'Siêu âm ổ bụng', price: '300.000₫', image: '🔬' },
    { name: 'Khám nha khoa', price: '200.000₫', image: '🦷' },
    { name: 'Tẩy trắng răng laser', price: '2.500.000₫', image: '✨' },
  ],
  pharmacy_store: [
    { name: 'Panadol Extra 12 viên', price: '35.000₫', image: '💊' },
    { name: 'Vitamin C DHC 30 ngày', price: '120.000₫', image: '💊', tag: 'Bán chạy' },
    { name: 'Thuốc ho Prospan 100ml', price: '95.000₫', image: '🧴' },
    { name: 'Nước muối sinh lý NaCl', price: '15.000₫', image: '💧' },
    { name: 'Khẩu trang y tế hộp 50', price: '45.000₫', image: '😷' },
  ],
  company_site: [
    { name: 'Dịch vụ tư vấn chiến lược', price: 'Liên hệ', image: '📊' },
    { name: 'Giải pháp chuyển đổi số', price: 'Liên hệ', image: '💻', tag: 'Mới' },
    { name: 'Dịch vụ kế toán trọn gói', price: '3.500.000₫/tháng', image: '📋' },
    { name: 'Dịch vụ marketing tổng hợp', price: '10.000.000₫/tháng', image: '📈' },
    { name: 'Thiết kế nhận diện thương hiệu', price: '15.000.000₫', image: '🎨' },
  ],
  baby_store: [
    { name: 'Sữa bột Similac IQ 900g', price: '490.000₫', image: '🍼', tag: 'Bán chạy' },
    { name: 'Bỉm Merries size L 54 miếng', price: '350.000₫', image: '👶' },
    { name: 'Xe đẩy gấp gọn Combi', price: '3.990.000₫', image: '🚼' },
    { name: 'Đồ chơi xếp hình Lego Duplo', price: '590.000₫', image: '🧸' },
    { name: 'Áo liền quần cotton organic', price: '199.000₫', image: '👕' },
  ],
  sports_store: [
    { name: 'Giày chạy Nike Pegasus 41', price: '3.490.000₫', image: '👟', tag: 'Mới' },
    { name: 'Bóng đá Adidas Champions', price: '990.000₫', image: '⚽' },
    { name: 'Vợt cầu lông Yonex', price: '1.890.000₫', image: '🏸' },
    { name: 'Quần short thể thao', price: '290.000₫', image: '🩳' },
    { name: 'Bình nước gym 1.5L', price: '190.000₫', image: '💪' },
  ],
  pet_store: [
    { name: 'Thức ăn Royal Canin 2kg', price: '390.000₫', image: '🐕', tag: 'Bán chạy' },
    { name: 'Cát vệ sinh mèo 10L', price: '150.000₫', image: '🐱' },
    { name: 'Vòng cổ LED chống lạc', price: '190.000₫', image: '📿' },
    { name: 'Lồng vận chuyển thú cưng', price: '490.000₫', image: '🏠' },
    { name: 'Đồ chơi gặm sạch răng', price: '89.000₫', image: '🦴' },
  ],
  farm_store: [
    { name: 'Gạo hữu cơ Quảng Trị 5kg', price: '159.000₫', image: '🌾', tag: 'Organic' },
    { name: 'Mật ong rừng nguyên chất 500ml', price: '290.000₫', image: '🍯' },
    { name: 'Trà shan tuyết Hà Giang', price: '350.000₫', image: '🍵' },
    { name: 'Cà phê Arabica Đà Lạt 500g', price: '190.000₫', image: '☕' },
    { name: 'Hạt điều rang muối 500g', price: '180.000₫', image: '🥜' },
  ],
  landing_page: [
    { name: 'Sản phẩm chủ lực', price: '999.000₫', image: '🎯', tag: 'Best Seller' },
    { name: 'Combo tiết kiệm x3', price: '2.499.000₫', image: '📦' },
    { name: 'Phiên bản giới hạn', price: '1.499.000₫', image: '⭐' },
    { name: 'Gói dùng thử', price: '199.000₫', image: '🎁' },
  ],
};
