project_id = "rodpbhesrwykmpywiiyd"

[functions.register-tenant]
verify_jwt = false

[functions.approve-payment]
verify_jwt = false

[functions.manage-tenant]
verify_jwt = false

[functions.send-password-reset]
verify_jwt = false