import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers":
    "authorization, x-client-info, apikey, content-type, x-supabase-client-platform, x-supabase-client-platform-version, x-supabase-client-runtime, x-supabase-client-runtime-version",
};

interface OrderRow {
  orderId: string; // Auto-generated by frontend (e.g. AUTO-000001)
  imei: string;
  customerName: string;
  customerPhone: string;
  customerEmail: string;
  customerAddress: string;
  productName: string; // Full name including variant (e.g. "iPhone 15 Pro Max 256GB Đen")
  productVariant: string; // Deprecated - kept for backward compatibility
  salePrice: number;
  note: string;
  orderDate: string;
  status: string;
  warranty: string;
  // Optional multi-item support (KiotViet style: 1 invoice = many products)
  items?: Array<{
    productName: string;
    sku?: string;
    imei?: string;
    salePrice: number;
    quantity?: number;
    warranty?: string;
    note?: string;
  }>;
  totalAmount?: number; // explicit invoice total (overrides salePrice if provided)
}

function parseDate(dateStr: string): string {
  try {
    if (!dateStr) return new Date().toISOString();
    // Already ISO datetime → keep as-is (preserves exact time)
    if (/^\d{4}-\d{2}-\d{2}T/.test(dateStr)) {
      const d = new Date(dateStr);
      if (!isNaN(d.getTime())) return d.toISOString();
    }
    // dd/mm/yyyy [hh:mm[:ss]]
    const m = dateStr.trim().match(/^(\d{1,2})\/(\d{1,2})\/(\d{4})(?:\s+(\d{1,2}):(\d{2})(?::(\d{2}))?)?$/);
    if (m) {
      const [, dd, mm, yyyy, hh, mi, ss] = m;
      const iso = `${yyyy}-${mm.padStart(2, "0")}-${dd.padStart(2, "0")}T${(hh || "12").padStart(2, "0")}:${(mi || "00").padStart(2, "0")}:${(ss || "00").padStart(2, "0")}+07:00`;
      const d = new Date(iso);
      if (!isNaN(d.getTime())) return d.toISOString();
    }
    const parts = dateStr.split("/");
    if (parts.length === 3) {
      return `${parts[2]}-${parts[1].padStart(2, "0")}-${parts[0].padStart(2, "0")}T12:00:00+07:00`;
    }
  } catch { /* ignore */ }
  return new Date().toISOString();
}

function cleanImei(raw: string | null | undefined): string | null {
  const v = raw?.trim() || null;
  if (!v || v === "-" || v === "empty" || v.startsWith("empty")) return null;
  return v;
}

Deno.serve(async (req) => {
  if (req.method === "OPTIONS") {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const authHeader = req.headers.get("Authorization");
    if (!authHeader) {
      return new Response(JSON.stringify({ error: "Unauthorized" }), {
        status: 401, headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    const supabaseUrl = Deno.env.get("SUPABASE_URL")!;
    const supabaseServiceKey = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;

    const userClient = createClient(supabaseUrl, Deno.env.get("SUPABASE_ANON_KEY")!, {
      global: { headers: { Authorization: authHeader } },
    });
    const { data: { user }, error: authError } = await userClient.auth.getUser();
    if (authError || !user) {
      return new Response(JSON.stringify({ error: "Unauthorized" }), {
        status: 401, headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    const { data: tenantId } = await userClient.rpc("get_user_tenant_id_secure");
    if (!tenantId) {
      return new Response(JSON.stringify({ error: "Tenant not found" }), {
        status: 400, headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    const { data: isAdmin } = await userClient.rpc("is_tenant_admin", { _user_id: user.id });
    if (!isAdmin) {
      return new Response(JSON.stringify({ error: "Forbidden: Admin only" }), {
        status: 403, headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    const adminClient = createClient(supabaseUrl, supabaseServiceKey);
    const { orders, sourceId = "vphone1" }: { orders: OrderRow[]; sourceId?: string } = await req.json();

    if (!orders?.length) {
      return new Response(JSON.stringify({ error: "No orders provided" }), {
        status: 400, headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    // Get default branch
    const { data: branches } = await adminClient
      .from("branches").select("id").eq("tenant_id", tenantId).eq("is_default", true).limit(1);
    const defaultBranchId = branches?.[0]?.id || null;

    // Filter completed orders only
    const completedOrders = orders.filter(
      (o) => o.status === "Hoàn tất" || o.status === "Đã giao hàng"
    );

    // --- STEP 1: Batch fetch existing receipt codes to skip duplicates ---
    const allCodes = completedOrders.map(o => `${sourceId.toUpperCase()}-${o.orderId.slice(-8)}`);
    const existingCodesSet = new Set<string>();
    // Fetch in chunks of 500 to avoid query size limits
    for (let i = 0; i < allCodes.length; i += 500) {
      const chunk = allCodes.slice(i, i + 500);
      const { data: existing } = await adminClient
        .from("export_receipts").select("code").eq("tenant_id", tenantId).in("code", chunk);
      existing?.forEach(r => existingCodesSet.add(r.code));
    }

    // --- STEP 2: Collect unique phones and batch upsert customers ---
    const phoneMap = new Map<string, { name: string; email: string; address: string; phone: string }>();
    for (const o of completedOrders) {
      if (o.customerPhone?.length >= 9) {
        const cleaned = o.customerPhone.replace(/\s+/g, "");
        if (!phoneMap.has(cleaned)) {
          phoneMap.set(cleaned, {
            name: o.customerName || "Khách lẻ",
            email: o.customerEmail || "",
            address: o.customerAddress || "",
            phone: cleaned,
          });
        }
      }
    }

    const customerIdMap = new Map<string, string>();
    const allPhones = [...phoneMap.keys()];
    
    // Batch fetch existing customers
    for (let i = 0; i < allPhones.length; i += 500) {
      const chunk = allPhones.slice(i, i + 500);
      const { data: existingCusts } = await adminClient
        .from("customers").select("id, phone").eq("tenant_id", tenantId).in("phone", chunk);
      existingCusts?.forEach(c => customerIdMap.set(c.phone, c.id));
    }

    // Batch insert new customers
    const newCustomers = allPhones
      .filter(p => !customerIdMap.has(p))
      .map(p => {
        const info = phoneMap.get(p)!;
        return { name: info.name, phone: info.phone, email: info.email || null, address: info.address || null, tenant_id: tenantId, source: sourceId };
      });

    if (newCustomers.length > 0) {
      // Insert in chunks of 200
      for (let i = 0; i < newCustomers.length; i += 200) {
        const chunk = newCustomers.slice(i, i + 200);
        const { data: inserted, error: custErr } = await adminClient
          .from("customers").insert(chunk).select("id, phone");
        if (custErr) {
          console.error("Batch customer insert error:", custErr);
        } else {
          inserted?.forEach(c => customerIdMap.set(c.phone, c.id));
        }
      }
    }

    // --- STEP 3: Batch insert receipts and items ---
    let createdReceipts = 0;
    let createdItems = 0;
    let skipped = 0;

    // Prepare non-duplicate orders
    const newOrders = completedOrders.filter(o => {
      const code = `${sourceId.toUpperCase()}-${o.orderId.slice(-8)}`;
      if (existingCodesSet.has(code)) { skipped++; return false; }
      return true;
    });

    // Process in chunks of 200 receipts at a time
    const CHUNK = 200;
    for (let i = 0; i < newOrders.length; i += CHUNK) {
      const chunk = newOrders.slice(i, i + CHUNK);

      const receiptRows = chunk.map(order => {
        const cleanPhone = order.customerPhone?.replace(/\s+/g, "") || "";
        const total = typeof order.totalAmount === "number" && order.totalAmount > 0
          ? order.totalAmount
          : (order.items && order.items.length
              ? order.items.reduce((s, it) => s + (Number(it.salePrice) || 0) * (Number(it.quantity) || 1), 0)
              : (order.salePrice || 0));
        return {
          code: `${sourceId.toUpperCase()}-${order.orderId.slice(-8)}`,
          tenant_id: tenantId,
          customer_id: customerIdMap.get(cleanPhone) || null,
          branch_id: defaultBranchId,
          export_date: parseDate(order.orderDate),
          total_amount: total,
          paid_amount: total,
          debt_amount: 0,
          vat_amount: 0,
          vat_rate: 0,
          status: "completed",
          note: `[${sourceId}] ${order.note || ""}`.trim(),
          created_by: user.id,
        };
      });

      const { data: insertedReceipts, error: receiptErr } = await adminClient
        .from("export_receipts").insert(receiptRows).select("id, code");

      if (receiptErr) {
        console.error("Batch receipt insert error:", receiptErr);
        skipped += chunk.length;
        continue;
      }

      createdReceipts += insertedReceipts.length;

      // Map code -> receipt id
      const codeToId = new Map(insertedReceipts.map(r => [r.code, r.id]));

      // Build items
      const itemRows: any[] = [];
      for (const order of chunk) {
        const code = `${sourceId.toUpperCase()}-${order.orderId.slice(-8)}`;
        const receiptId = codeToId.get(code);
        if (!receiptId) continue;
        const list = order.items && order.items.length
          ? order.items
          : [{
              productName: order.productName,
              sku: order.productVariant,
              imei: order.imei,
              salePrice: order.salePrice,
              warranty: order.warranty,
              note: order.note,
            }];
        for (const it of list) {
          const qty = Math.max(1, Number(it.quantity) || 1);
          for (let q = 0; q < qty; q++) {
            itemRows.push({
              receipt_id: receiptId,
              product_name: it.productName || "Sản phẩm",
              sku: it.sku || "",
              imei: cleanImei(it.imei),
              sale_price: Number(it.salePrice) || 0,
              status: "sold",
              warranty: it.warranty || null,
              note: it.note || null,
            });
          }
        }
      }

      if (itemRows.length > 0) {
        const { error: itemErr } = await adminClient
          .from("export_receipt_items").insert(itemRows);
        if (itemErr) {
          console.error("Batch item insert error:", itemErr);
        } else {
          createdItems += itemRows.length;
        }
      }
    }

    return new Response(
      JSON.stringify({
        success: true,
        totalOrders: orders.length,
        completedOrders: completedOrders.length,
        createdReceipts,
        createdItems,
        customersCreated: newCustomers.length,
        skipped,
      }),
      { status: 200, headers: { ...corsHeaders, "Content-Type": "application/json" } }
    );
  } catch (err) {
    console.error("Error:", err);
    return new Response(JSON.stringify({ error: err.message }), {
      status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" },
    });
  }
});
